# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /rusty-bio

# Site live URL
# url: http://delagoya.github.io

# Localhost 
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Rusty Bioinformatics
  # Little description about your site
  description:  Back to the basics of bioinformatics.
  meta_description: Me (re)learning programming in bioinformatics concepts
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Angel Pizarro
    email: delagoya@gmail.com
    url: http://delagoya.github.io

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: delagoya
    twitter: delagoya
    gplus: 107123789381974740251
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
